### ISSUE TITLE
Crash when trying to create an unsupported adventure

### ISSUE THREAD

**Issue by sebhz** [joaomneto/TitanCompanion#87]
Create a new adventure, chose an unsupported book. Titan Companion crashes.
I did not like the "Book not supported" popup, but this is worse :-)

Tested on 0.30-beta. English locale. Android 6.0.1.

**Comment by sebhz** [comment]
Logcat says :

```
08-28 22:11:10.611 13825 13825 E AndroidRuntime: FATAL EXCEPTION: main
08-28 22:11:10.611 13825 13825 E AndroidRuntime: Process: pt.joaomneto.titancompanion, PID: 13825
08-28 22:11:10.611 13825 13825 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;
```

Per https://stackoverflow.com/questions/45604099/rxjavaplugins-error-didnt-find-class-com-google-devtools-build-android-desugar/45609518#45609518 this seems to be a problem with Android Studio.
Upgrading to 3.0-beta2 fixed it for me. According to stackoverflow, beta3 broke it again (but I did not check)

**Comment by joaomneto** [comment]
I just found this issue also when creating espresso testing. It's a missing class. I'm going to add it to the master branch ASAP and it should fix the problem for all versions of Android Studio. However it is merely hiding an exception. There's still an error to be fixed there... I'm adding the project do CircleCI in order to perform continuous integration running a batch of espresso tests, hopefully covering the entire app. I think this will finally solve all the regression errors I've been introducing... 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by joaomneto** [comment]
Fixed by adding a code path to the app with the missing class. To be removed in the future as Android Studio goes to full production in v3.0
